### ISSUE TITLE
Kebechet update manager: KeyError on kebechet_runners.py:210

### ISSUE THREAD

**Issue by KPostOffice** [thoth-station/support#147] opened 2021-11-18 14:20 UTC
## Description
This is an automated issue generated by Kebechet v1.6.5. The update manager threw an exception (KeyError)
at runtime while working on the following repository https://github.com/KPostOffice/khebhut_test

## Traceback
```python
Traceback (most recent call last):
  File "/home/kpostlet/thoth-all/thoth-station/kebechet/kebechet/kebechet_runners.py", line 210, in run
    instance.run(**manager_configuration)
  File "/home/kpostlet/thoth-all/thoth-station/kebechet/kebechet/managers/update/update.py", line 1039, in run
    body=ISSUE_NO_DEPENDENCY_MANAGEMENT.format(env_name=e),
KeyError: 'environment_name'

```

**Comment by goern** [comment] 2021-11-22 17:28
/kind bug
/triage duplicate
#96
/close

**Comment by codificat** [comment] 2021-11-22 22:36
/reopen
/remove-triage duplicate
/triage accepted
/priority important-soon

this isn't a duplicate of #96, it's a different problem.

It seems to be a small oversight in https://github.com/thoth-station/kebechet/pull/867 :

```python
                                body=ISSUE_NO_DEPENDENCY_MANAGEMENT.format(env_name=e),
```
https://github.com/thoth-station/kebechet/blob/2d65f91577637f5de75d3dcdbf324d0c81951ab0/kebechet/managers/update/update.py#L1039

vs 

```python
ISSUE_NO_DEPENDENCY_MANAGEMENT = """No dependency management found for the {environment_name} environment. If you want
```
https://github.com/thoth-station/kebechet/blob/2d65f91577637f5de75d3dcdbf324d0c81951ab0/kebechet/managers/update/messages.py#L147

/assign @KPostOffice

**Closed** 2021-11-25 12:15 UTC
Labels: kind/bug, triage/accepted, priority/important-soon
